//
// Created by carlo on 10/06/2016.
//

#ifndef CURSO_C_INCLUDES_HPP
#define CURSO_C_INCLUDES_HPP

//#include "01-TiposDeDatos.cpp"
//#include "02-ConstantesYModificadores.cpp"
#include "03-Operadores.cpp"
//#include "04-ClasesDeAlmacenamiento.cpp"
//#include "05-Selectivas.cpp"
//#include "06-Iterativas.cpp"
//#include "07-Funciones.cpp"
//#include "08-Numeros.cpp"
//#include "09-Arreglos.cpp"
//#include "10-Cadenas.cpp"
//#include "11-Punteros.cpp"
//#include "12-Referencias.cpp"
//#include "13-TiempoHora.cpp"
//#include "14-EntradasSalidas.cpp"
//#include "15-Estructuras.cpp"
//#include "16-Clases.cpp"
//#include "17-Sobrecarga.cpp"
//#include "18-Polimorfismo.cpp"
//#include "19-Archivos.cpp"
//#include "20-Excepciones.cpp"
//#include "21-MemoriaDinamica.cpp"
//#include "22-Namespace.cpp"
//#include "23-Templates.cpp"
//#include "24-Preprocesador.cpp"
//#include "25-Lambda.cpp"
//#include "26-ControlesVirtuales.cpp"
//#include "27-Decltype.cpp"
//#include "28-Ordenamientos.cpp"
//#include "29-Busquedas.cpp"
//#include "31-Lista.cpp"
//#include "32-Pila.cpp"
//#include "33-Cola.cpp"
//#include "34-Vector.cpp"
//#include "35-Maps.cpp"
//#include "36-Sets.cpp"
//#include "37-Arbol.cpp"
//#include "38-Grafo.cpp"
//#include "39-VoidApuntador.cpp"
//#include "40-Functores.cpp"
//#include "41-Cpp11.cpp"
//#include "42-Cpp14.cpp"

#endif //CURSO_C_INCLUDES_HPP
